name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '**.md' # Ignore markdown changes for CI
  pull_request:
    branches:
      - main
      - develop
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # --- Setup PHP Environment (WordPress Plugin) ---
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql, curl, json, gd, xml
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: none

      - name: Install PHP Dependencies (Plugin)
        run: composer install --no-interaction --prefer-dist
        working-directory: ./wp-ict-platform

      - name: PHP Lint (PHPCS)
        run: vendor/bin/phpcs -q --report=full || true
        working-directory: ./wp-ict-platform

      # - name: PHP Unit Tests (optional)
      #   run: vendor/bin/phpunit
      #   working-directory: ./wp-ict-platform

      # --- Setup Node.js for Plugin Admin UI ---
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Node Dependencies (Plugin UI)
        run: npm ci
        working-directory: ./wp-ict-platform

      - name: Validate OpenAPI Spec (Plugin)
        run: npm run api:validate
        working-directory: ./wp-ict-platform

      - name: Generate API Types (Plugin)
        run: npm run api:types
        working-directory: ./wp-ict-platform

      - name: ESLint (Plugin UI)
        run: npm run lint
        working-directory: ./wp-ict-platform

      - name: Prettier Check (Plugin UI)
        run: npm run format:check || true
        working-directory: ./wp-ict-platform

      - name: Jest Tests (Plugin UI)
        run: npm test -- --coverage
        working-directory: ./wp-ict-platform

      - name: Build Admin Assets (Plugin UI)
        run: npm run build
        working-directory: ./wp-ict-platform

      # --- Mobile App (basic checks) ---
      - name: Install Node Dependencies (Mobile App)
        run: npm ci
        working-directory: ./ict-mobile-app

      - name: Generate API Types (Mobile App)
        run: npm run api:types
        working-directory: ./ict-mobile-app

      - name: Type Check (Mobile App)
        run: npm run type-check
        working-directory: ./ict-mobile-app

      - name: Jest Tests (Mobile App)
        run: npm test -- --coverage
        working-directory: ./ict-mobile-app

      # --- Publish OpenAPI artifact ---
      - name: Upload OpenAPI Spec
        uses: actions/upload-artifact@v3
        with:
          name: openapi-spec
          path: wp-ict-platform/docs/openapi.yaml

      # --- Optional: SQL Linting (if you have separate SQL files) ---
      # - name: Install SQLFluff
      #   run: pip install sqlfluff
      # - name: Run SQLFluff Lint
      #   # Adjust path to your SQL files.
      #   run: sqlfluff lint ./sql
      #   continue-on-error: true

      # --- Optional: End-to-End (E2E) Tests ---
      # - name: Run E2E Tests
      #   # This step typically requires your application to be running.
      #   # You might need to add steps to start your backend and frontend services.
      #   run: npm run e2e # e.g., Cypress, Playwright
      #   working-directory: ./e2e-tests # Or wherever your E2E tests reside
      #   env:
      #     BASE_URL: http://localhost:3000 # Your application's URL for E2E tests
